name: Deploy Next.js Example to GitHub Pages

on:
  push:
    branches:
      - main # or master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        # Install dependencies in both root and example-nextjs directory
        run: |
          npm ci
          cd example-nextjs
          npm ci

      - name: Build
        # Build the Next.js example app
        run: |
          cd example-nextjs
          npm run build

      - name: Add .nojekyll file
        # Prevent Jekyll processing for GitHub Pages
        run: |
          touch example-nextjs/out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: example-nextjs/out
          branch: gh-pages
