name: Publish Package

on:
  workflow_run:
    workflows: ['Build and Test'] # Name of your main build workflow
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if build succeeded
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for version calculation

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Get latest beta version
        id: get-version
        run: |
          LATEST_VERSION=$(npm view ${{ github.event.repository.name }}@0.1.0-beta versions --json 2>/dev/null | jq -r '.[-1]' || echo "0.1.0-beta.0")
          if [ "$LATEST_VERSION" = "null" ]; then
            LATEST_VERSION="0.1.0-beta.0"
          fi
          BETA_NUM=$(echo $LATEST_VERSION | grep -o 'beta\.[0-9]*' | cut -d'.' -f2)
          NEXT_BETA=$((BETA_NUM + 1))
          NEXT_VERSION="0.1.0-beta.$NEXT_BETA"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: npm version ${{ steps.get-version.outputs.next_version }} --no-git-tag-version

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTOMATION_TOKEN }}" > .npmrc
          npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
